config/routes.rb
Rails.application.routes.draw do
  scope ":locale" do
    get 'home/index'
    get 'home/contact'
    get 'project/index'
    get 'project/rubyrubyruby'
    get 'home/contact'
    get 'project/healthyworkers'
    get 'home/curriculum'
    resources :posts
    match '/contacts',     to: 'contacts#new',             via: 'get'
    resources "contacts", only: [:new, :create]
end

  root 'home#index'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "dimmaaah@live.nl",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_local

  private

  def set_local
   I18n.locale = params[:locale] if params[:locale].present?
  end

def default_url_options(options = {})
  {locale: I18n.locale}

end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def curriculum
  end

  def projects
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
	def index
	end

	def rubyrubyruby	
	end

	def healthyworkers
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div align="center">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/home/contact.html.erb
<div class="container">
	<h1>WHAT DO YOU WANt?</h1>

	<p>If you fill in and submit this form, you'll contact me directly by sending an email to my personal email account. Looking forward to receiving your message so let me know what you want or need from me.</p>

	<form>
	  <div class="form-group">
	    <label for="formGroupExampleInput">Example label</label>
	    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Please state your business">
	  </div>
	    <div class="form-group">
	    <label for="formGroupExampleInput">Example label</label>
	    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="What is your name?">
	  </div>
	  <div class="form-group">
	    <label for="formGroupExampleInput2">Another label</label>
	    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input">
	    <br>

	    <button type="submit" class="btn btn-primary">Submit</button>
	  </div>
	</form>
</div>

app/views/home/curriculum.html.erb
<div class="container-fluid boos">
  <div class="row">
  <div class="space"></div>
  <div class="container now">
  <div class="row">
    <div class="col-md-12 pic">
      <div class="container pad">
      <div class="row">
        <div class="col-md-6">
        <div class="col-content">
          <%= image_tag("daemien", :alt => "rss feed", class: "profilepic") %>
          </div>
        </div>
        <div class="col-md-6">
        <div class="col-content-info">
          <div class="pinfo">
          <h2>Daemien Hope</h2>
          <h4>Junior Ruby fullstack developer</h4>
          <hr>
          <div class="row">
            <ul class="pinfo col-md-4 col-xs-4">
              <li>Date of birth:</li>
              <li>Address:</li>
              <li>Email:</li>
              <li>Phone:</li>
              <li>LinkedIn:</li>
              <li>Github:</li>
              <li>Drivers License:</li>
            </ul>
            <ul class="pinfo-a col-md-6 col-xs-6">
              <li>March 16, 1991</li>
              <li>Comeniusstraat 189 Amsterdam</li>
              <li>daemienho@yahoo.nl</li>
              <li>+31 611287858</li>
              <li><%= link_to "linkedin.com/in/daemien-ho", "http://linkedin.com/in/daemien-ho", class: "remove_link" %></li>
              <li><%= link_to "github.com/dimmaaah", "http://github.com/dimmaaah", class: "remove_link" %></li>
              <li>Car (B)</li>
            </ul>
            </div>
            <br>
           </div>
           </div>
           </div>
         </div>
        </div>
      </div>
  </div>
    <div class="col-xs-12 col-md-6">
      
      <div class="m">
       <h3><%= t 'info.motivationtitle' %></h3>
       <p><%= t 'info.motivationdes' %></p>
      </div>
  <hr>
      <div class="V">
     <h3><%= t 'info.skillstitle' %></h1>
      <p><%= t 'info.skillsdes' %></p>
      <p class="em">Front-End</p>
      <div class="iconss">
        <i class="devicon-html5-plain-wordmark colored"></i>
        <i class="devicon-css3-plain-wordmark colored"></i>
        <i class="devicon-bootstrap-plain-wordmark colored"></i>
        <i class="devicon-jquery-plain-wordmark colored"></i>
      </div>
      <p class="em">Back-End</p>
      <div class="iconss">
        <i class="devicon-ruby-plain-wordmark colored"></i>
        <i class="devicon-rails-plain-wordmark colored"></i>
        <i class="devicon-postgresql-plain-wordmark colored"></i>
        <i class="devicon-github-plain-wordmark colored"></i>
      </div>
    </div>
      <hr>

     <div class="ed">
       <h3><%= t 'info.educationtitle' %></h3>
       <p><%= t 'info.education.paragraph' %></p>
       <ul>
         <br>
         <li class="bold">Le Wagon Coding School(BSSA Startup School)</li>
         <p>Fullstack development - Le Wagon 2016</p>
         <p><%= t 'info.school.lewagon' %></p>
         <br>
         <li class="bold">Regio College Zaandam</li>
         <p>Retail business & management 2008 – 2010</p>
         <p><%= t 'info.school.regio' %></p> 
         <br>
         <li class="bold">Amstellyceum</li>
         <p>Vmbo-T 2003-2008</p>
         <p><%= t 'info.school.amstel' %></p> 
       </ul>
       
     </div>

    </div>

    <div class="col-xs-12 col-md-6">
      <div class="projecten">
       <h3><%= t'info.projects.title' %></h3>
       <ul>
         <li class="bold">RubyRubyRuby</li>
         <p><%= t 'info.projects.ruby' %></p>
         <li class="bold">Healthy Workers</li>
         <p><%= t 'info.projects.healthy' %></p>
       </ul>
      </div>

  

<hr>
    <div class="xp">
        <h3><%= t 'info.title.xp' %></h3> 
        <p><%= t 'info.paragraph' %></p>
       <ul>
         <li class="bold">Randstad 2012 - 2017</li>
         <p><%= t 'info.xp.rand' %></p>
         <li class="bold">PostNL 2016</li>
         <p><%= t 'info.xp.post' %></p>
         <li class="bold">Dampkring 2012 - 2016</li>
         <p><%= t 'info.xp.damp' %></p>
         <li class="bold">NH-Hotel</li>
         <p><%= t 'info.xp.nh' %></p>
         <li class="bold">Laundry Industry</li>
         <p><%= t 'info.xp.damp' %></p>
         <li class="bold">Healthy Workers - 2016 </li>
         <p><%= t 'info.xp.healthy' %></p>
         <li class="bold">KVC Westerlo 2011 - 2012</li>
         <p><%= t 'info.xp.kvc' %></p>
         <li class="bold">VVV-Venlo 2010 - 2011</li>
         <p><%= t 'info.xp.vvv' %></p>
         <li class="bold">Levi's 2008 - 2010</li>
         <p><%= t 'info.xp.levi' %></p>
         <li class="bold">Bartsmit 2007 </li>
        <p><%= t 'info.xp.bart' %></p>
         <li class="bold">Bijenkorf 2003 - 2007</li>
         <p><%= t 'info.xp.bijen' %></p>
        </ul>
      </div>
     
    
  </div>
      

 <!--      <div class="col-md-6">
        <div class="logo_">
          <h4>Ruby on Rails</h4>
          <%= image_tag("logo1.png", :alt => "rss feed", class: "logol") %>
        </div>
        <div class="logo_">
          <h4>Javascript</h4>
          <%= image_tag("logo2.png", :alt => "rss feed", class: "logol") %>
        </div>
      </div> -->

      <!-- <div class="col-md-6">
       <div class="logo_">
        <h4>Bootstrap</h4>
        <%= image_tag("logo3.png", :alt => "rss feed", class: "logol") %>
      </div>
      <div class="logo_">
        <h4>HTML</h4>
        <%= image_tag("logo4.png", :alt => "rss feed", class: "logol") %>
      </div>
    </div> -->
    <!-- <div class="col-md-6">
     <div class="logo_">
      <h4>AJAX</h4>
      <%= image_tag("logo5.png", :alt => "rss feed", class: "logol") %>
    </div>
    <div class="logo_">
      <h4>CSS</h4>
      <%= image_tag("logo6.png", :alt => "rss feed", class: "logol") %>
    </div>
   </div>
  </div> -->
  


</div>

app/views/home/index.html.erb
<div class="picture_me">
  <div class="container">
  <H1 class="welcome">LOOKING FOR A RUBY ON RAILS DEVELOPER?</H1>
    <p><a id="readmore" href="" class="btn btn-default center">REad MoRE AbouT ME..</a></p>
  </div>
</div>
<!-- 
<a href="#" onclick="this.style.backgroundColor='#009900';this.style.color='#FFFFFF';">Paint it green</a> -->
<section>
<div class="white">
  <h2 id="about_me">Who Am I?</h2>
  <div class="container">
    <div id="section_about" class="row section_about" >
      
      <div class="col-md-6 col-sm-12">
        <%= image_tag("dims.png", :alt => "Me signing a contract", class: "pro_pic") %>
      </div>
      <div class="col-md-6 col-sm-12">
        <p><%= t 'index.about' %></p>
        <p><%= t 'index.about2' %></p>
        <p><%= link_to "Bekijk Mijn CV!", home_curriculum_path, class: "btn btn-danger pull-right" %></p>
      </div>
    </div>
  </div>
</div>
   <div class="grey">
      <h2 id="tools">My Development Environment Tools</h2>

  <div id="div_icons" class="div_icons grey">
    <ul class="icons">
      <li> <i class="devicon-html5-plain colored"></i></li>
      <li> <i class="devicon-ruby-plain colored"></i></li>
      <li> <i class="devicon-rails-plain colored"></i></li>
      <li> <i class="devicon-css3-plain colored"></i></li>
      <li> <i class="devicon-bootstrap-plain colored"></i></li>
      <li> <i class="devicon-ubuntu-plain colored"></i></li>
      <li> <i class="devicon-atom-original-wordmark colored"></i></li>
      <li> <i class="devicon-heroku-plain-wordmark colored"></i></li>
      <li> <i class="devicon-jquery-plain-wordmark colored"></i></li>
      <li> <i class="devicon-postgresql-plain-wordmark colored"></i></li>
      <li> <i class="devicon-trello-plain-wordmark"></i></li>
      <li> <i class="devicon-vim-plain"></i></li>
      <li> <i class="devicon-firefox-plain-wordmark colored"></i></li>
    </ul>
  </div>
   </div>
</section>

  
<!--
<section>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12 col-md-6"><h1 class="pnav">curriculum vitea</h1>
        <div class="jumbotron jumbotron-fluid">
          <div class="container">
            <h2 class="display-3">curriculum vitea</h2>
            <p class="lead"><%= t 'card.cv' %></p>

            <%= link_to "Check out CV.", home_curriculum_path, class: "btn btn-default" %>

             <%= link_to "Download CV.", home_curriculum_path, class: "btn btn-primary pull-right" %>
          </div>
        </div>
      </div>
      <div class="col-sm-12 col-md-6"><h1 class="pnav">Projects</h1>
         <div class="jumbotron jumbotron-fluid">
          <div class="container">
            <h2 class="display-3">Projects</h2>
            <p class="lead"><%= t 'card.portofolio' %></p>
            <%= link_to "Check out the Projects.", project_index_path, class: "btn btn-default" %>

          </div>
        </div>
      </div>
      <div class="col-sm-12 col-md-12"><h1 class="pnav">Contact</h1>
         <div class="jumbotron jumbotron-fluid">
          <div class="container">
            <h2 class="display-3">Meet Me</h2>
            <p class="lead"><%= t 'card.contact' %></p>
            <%= link_to "Contact Me.", home_contact_path, class: "btn btn-danger" %>


          </div>
        </div>
      </div>
    </div>
  </div>
</section>

-->

<!--

<div class="container">
  <h1 id="about_me">About me!</h1>

  <ul class="nav nav-pills nav-justified">
    <li><a href="#about" data-toggle="tab">My Story</a></li>
    <li><a href="#history" data-toggle="tab">My history</a></li>
    <li><a href="#goals" data-toggle="tab">My Goals</a></li>
  </ul>

    <div class="tab-content">

      <div class="tab-pane" id="about">
        <div class="about_me">
          <%= image_tag "mohammed.jpg", class: "intro_pic" %>
            <p>Mijn naam is Daemien Ho en ik ben Ruby developer. Ik ben 25 jaar jong en ik
            </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur dolores quis nisi architecto. Voluptatibus in debitis delectus fugit neque accusamus tempora, repellendus sit quia enim nostrum nulla expedita recusandae ex!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque possimus ratione placeat fugit nemo, debitis sapiente, explicabo dicta vitae ad et quo in! Perspiciatis asperiores error laboriosam, officiis accusamus repellat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates itaque tempore accusamus labore incidunt alias cupiditate corporis officiis sequi quo dolor culpa error, suscipit perferendis minus reprehenderit, aliquam sit nihil
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae architecto distinctio officia quam praesentium, nesciunt provident, doloremque sit harum deserunt eum quaerat, accusantium qui! Beatae illo molestias, magni excepturi iste.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam aliquid deleniti quis accusamus numquam possimus expedita esse dolores harum deserunt reiciendis id repellat cupiditate fuga saepe labore vel, incidunt reprehenderit?.</p>


            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur dolores quis nisi architecto. Voluptatibus in debitis delectus fugit neque accusamus tempora, repellendus sit quia enim nostrum nulla expedita recusandae ex!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque possimus ratione placeat fugit nemo, debitis sapiente, explicabo dicta vitae ad et quo in! Perspiciatis asperiores error laboriosam, officiis accusamus repellat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates itaque tempore accusamus labore incidunt alias cupiditate corporis officiis sequi quo dolor culpa error, suscipit perferendis minus reprehenderit, aliquam sit nihil
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae architecto distinctio officia quam praesentium, nesciunt provident, doloremque sit harum deserunt eum quaerat, accusantium qui! Beatae illo molestias, magni excepturi iste. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti tenetur temporibus sapiente dolorum cumque quod maxime accusantium, modi facere qui amet similique ad laborum, totam, maiores. Adipisci earum pariatur, sequi.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, architecto. Blanditiis optio, culpa, ipsa hic magni maxime omnis facilis nobis error vero dolorum, alias non ipsum at adipisci, laborum quam?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam aliquid deleniti quis accusamus numquam possimus expedita esse dolores harum deserunt reiciendis id repellat cupiditate fuga saepe labore vel, incidunt reprehenderit?.</p>
          </div>
               <i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>
            <span class="sr-only">Loading...</span>
      </div>

      <div class="tab-pane" id="history">
        <div class="container">

          <p>Mijn naam is Daemien Ho en ik ben Ruby developer. Ik ben 25 jaar jong en ik
              </p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur dolores quis nisi architecto. Voluptatibus in debitis delectus fugit neque accusamus tempora, repellendus sit quia enim nostrum nulla expedita recusandae ex!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque possimus ratione placeat fugit nemo, debitis sapiente, explicabo dicta vitae ad et quo in! Perspiciatis asperiores error laboriosam, officiis accusamus repellat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates itaque tempore accusamus labore incidunt alias cupiditate corporis officiis sequi quo dolor culpa error, suscipit perferendis minus reprehenderit, aliquam sit nihil
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae architecto distinctio officia quam praesentium, nesciunt provident, doloremque sit harum deserunt eum quaerat, accusantium qui! Beatae illo molestias, magni excepturi iste.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam aliquid deleniti quis accusamus numquam possimus expedita esse dolores harum deserunt reiciendis id repellat cupiditate fuga saepe labore vel, incidunt reprehenderit?.</p>


              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur dolores quis nisi architecto. Voluptatibus in debitis delectus fugit neque accusamus tempora, repellendus sit quia enim nostrum nulla expedita recusandae ex!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque possimus ratione placeat fugit nemo, debitis sapiente, explicabo dicta vitae ad et quo in! Perspiciatis asperiores error laboriosam, officiis accusamus repellat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates itaque tempore accusamus labore incidunt alias cupiditate corporis officiis sequi quo dolor culpa error, suscipit perferendis minus reprehenderit, aliquam sit nihil
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae architecto distinctio officia quam praesentium, nesciunt provident, doloremque sit harum deserunt eum quaerat, accusantium qui! Beatae illo molestias, magni excepturi iste. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti tenetur temporibus sapiente dolorum cumque quod maxime accusantium, modi facere qui amet similique ad laborum, totam, maiores. Adipisci earum pariatur, sequi.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, architecto. Blanditiis optio, culpa, ipsa hic magni maxime omnis facilis nobis error vero dolorum, alias non ipsum at adipisci, laborum quam?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam aliquid deleniti quis accusamus numquam possimus expedita esse dolores harum deserunt reiciendis id repellat cupiditate fuga saepe labore vel, incidunt reprehenderit?.</p>


          <p>Here is some text to test my programming skills stolen from youtube 2</p>
        </div>
      </div>
      <div class="tab-pane" id="goals">
        <p>Here is some text to test my programming skills stolen from youtube 3</p>
      </div>
    </div>
  </a>
</div>

-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dimma</title>
   <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/master/devicon.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

</head>
<body>
 	<%= render "shared/navbar" %>
    	<%= yield %>

<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12">
        <ul class="social-buttons"></ul>
          <li class="social-button"></li><%= link_to root_path, class: "social_links2" do %>
          <%= content_tag(:i, "", class: "fa fa-home fa-3x") %>
          <% end %></li>
          <li class="social-button"></li><%= link_to "http://linkedin.com/in/daemien-ho", class: "social_links2" do %>
              <%= content_tag(:i, "", class: "fa fa-linkedin fa-3x") %>
              <% end %></li>
          <li class="social-button"></li><%= link_to home_contact_path, class: "social_links2" do %>
              <%= content_tag(:i, "", class: "fa fa-envelope fa-3x") %>
              <% end %></li>
          <li class="social-button"></li><%= link_to "https://github.com/Dimmaaah", class: "social_links2" do %>
                <%= content_tag(:i, "", class: "fa fa-github fa-3x") %>
                <% end %></li>
        </ul>
      </div>
    </div>
  </div>
</div>



   <script type="text/javascript">
   $(document).ready(function() {
  $('#section_about').hide(function() {
    $('.white, #readmore').mouseenter(function() {
      $('#section_about').show(3000)
    });
  });
});

  $(document).ready(function() {
    $('#div_icons').hide(function() {
      $('#tools').mouseenter(function() {
        $('#div_icons').slideDown("fast")
      });
    });
  });

$(document).ready(function() {
  $("#seemore").on("mouseenter", function() {
    $("html,body").animate({"scrollTop":$("#new").offset().top},1500);
    return false;
  });
});


$(function() {
  $("#readmore").on("mouseenter", function() {
    $("html,body").animate({"scrollTop":$("#about_me").offset().top},2500);
    return false;
  });
});
</script>
</body>
</html>

app/views/project/healthyworkers.html.erb
<div class="white">
	<div class="container">
		<h1>HealthyWorkers</h1>
		<div class="projects">
			<iframe src="https://player.vimeo.com/video/167265377" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
		</div>

		<p><%= t 'project.healthyworkers' %></p>
		<p><%= t 'project.healthyworkers_p2' %></p>
		<p><%= t 'project.healthyworkers_p3' %></p>

		<%= link_to(t('knop.bezoek2'), "http://rubyrubyruby.com", class: "btn btn-danger pull-right") %>
	</div>
</div>

app/views/project/index.html.erb
<div class="project_banner">
  <a id="seemore" href="#" class="btn btn-default">See All Projects!</a>
</div>
<div class="white">
<div class="container">
  <h1>Projects 2016</h1>
  <div id="new" class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <div class="card">
      <img class="card-img-top" src="<%= image_path('rubyrubyruby.png') %>" />
        <div class="card-block">
          <h4 class="card-title">RubyRubyRuby</h4>
          <p class="card-text">During my time as a student of Le Wagon Coding school. I've Developed a vacancy website especially made for Ruby developers.</p>
          <%= link_to "Check It", project_rubyrubyruby_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <div class="card">
      <img class="card-img-top" src="<%= image_path('healthyworkers.png') %>" />
      <div class="card-block">
        <h4 class="card-title">Healthy Workers</h4>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <%= link_to "Check It", project_healthyworkers_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/project/rubyrubyruby.html.erb
<div class="white">	
	<div class="container">
		<h1>RubyRubyRuby</h1>
		<div class="projects">
			<img class="card-img-top" src="<%= image_path('rubyrubyruby.png') %>" />
		</div>

		<p><%= t 'project.rubyrubyruby' %></p>
		<p><%= t 'project.rubyrubyruby_p2' %></p>
		<p><%= t 'project.rubyrubyruby_p3' %></p>

		<%= link_to(t('knop.bezoek'), "http://rubyrubyruby.com", class: "btn btn-danger pull-right") %>
	</div>
</div>

app/views/shared/_footer.html.erb
<div id="footer" class="footer">
  <div class="row">
    <div class="col-md-12">  
     <ul class="social_links">
      <li>
       <li><%= link_to root_path, class: "social_links2" do %>
        <%= content_tag(:i, "", class: "fa fa-home fa-3x") %>
        <% end %> </li>
         <li><%= link_to "http://linkedin.com/in/daemien-ho", class: "social_links2" do %>
        <%= content_tag(:i, "", class: "fa fa-linkedin fa-3x") %>
        <% end %> </li>
        <li><%= link_to home_contact_path, class: "social_links2" do %>
        <%= content_tag(:i, "", class: "fa fa-envelope fa-3x") %>
        <% end %> </li>

        <li><%= link_to "https://github.com/Dimmaaah", class: "social_links2" do %>
          <%= content_tag(:i, "", class: "fa fa-github fa-3x") %>
          <% end %> </li>
        </ul>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<nav id="nav_bar">
  <div class="navbar">
    <ul id="navbar-links">
      <li><%= link_to "DimmaaaH", home_index_path, class: "navbar_links" %></li>
      <li><%= link_to "Curriculum", home_curriculum_path, class: "navbar_links" %></li>
      <li><%= link_to "Projects", project_index_path, class: "navbar_links" %></li>
      <li><%= link_to "Contact", home_index_path, class: "navbar_links" %></li>
    
      <li class="pull-right"><%= link_to_unless_current image_tag("uk.png"), locale: "en" %></li>
      <li class="pull-right"><%= link_to_unless_current image_tag("nl.png"), locale: "nl" %></li>  
    </ul>
  </div>
</nav>